clear;
clc;
fileName = 'D:\Futures\Data\20131129\TempFile.xlsx';
volumeRange = 'w2:w20000';
bidPriceRange = 'q2:q20000';
directionRange = 'y2:y20000';
sheetName = 'sheet2';
volume=xlsread(fileName, sheetName, volumeRange);
bidPrice = xlsread(fileName, sheetName, bidPriceRange);
lastDirection = xlsread(fileName, sheetName, directionRange);
signedVolume = (volume)/100 + mean(bidPrice);
xAxis=1:length(bidPrice);
figure(1);
ax(1) = subplot(2,1,1);
plot(xAxis,bidPrice, 'black');
title('Bid Price');
grid ON;
ax(2) = subplot(2,1,2);
plot(xAxis, signedVolume, 'blue');
title('Volume');
grid ON;
linkaxes(ax,'x');