t = timer('TimerFcn',@myTimerCallback, 'ExecutionMode', 'fixedRate', 'Period', 1.0);
global index;
global data1;
global data2;
global data3;
global data4;
global data5;
global data6;
global data7;
global data8;
global windObj;
index = 1;
data1=[];
data2=[];
data3=[];
data4=[];
data5=[];
data6=[];
data7=[];
data8=[];
windObj = windmatlab;
start(t)