-- Create table
create tablespace marketdatatemp datafile 'D:\tablespaces\marketdatatemp.dbf' size 1M autoextend on next 64M;
create table temp_market_data_table
(
  data_type_version      NUMBER,
  time_stamp             TIMESTAMP(6),
  trading_day            VARCHAR2(9),
  instrument_id          VARCHAR2(11),
  exchange_id            VARCHAR2(9),
  exchange_instrument_id VARCHAR2(31),
  last_price             NUMBER,
  pre_settlement_price   NUMBER,
  pre_close_price        NUMBER,
  pre_open_interest      NUMBER,
  open_price             NUMBER,
  highest_price          NUMBER,
  lowest_price           NUMBER,
  volume                 NUMBER,
  turnover               NUMBER,
  open_interest          NUMBER,
  close_price            NUMBER,
  settlement_price       NUMBER,
  upper_limit_price      NUMBER,
  lower_limit_price      NUMBER,
  pre_delta              NUMBER,
  curr_delta             NUMBER,
  update_time            VARCHAR2(9),
  update_millisec        NUMBER,
  bid_price_1            NUMBER,
  bid_volume_1           NUMBER,
  ask_price_1            NUMBER,
  ask_volume_1           NUMBER,
  bid_price_2            NUMBER,
  bid_volume_2           NUMBER,
  ask_price_2            NUMBER,
  ask_volume_2           NUMBER,
  bid_price_3            NUMBER,
  bid_volume_3           NUMBER,
  ask_price_3            NUMBER,
  ask_volume_3           NUMBER,
  bid_price_4            NUMBER,
  bid_volume_4           NUMBER,
  ask_price_4            NUMBER,
  ask_volume_4           NUMBER,
  bid_price_5            NUMBER,
  bid_volume_5           NUMBER,
  ask_price_5            NUMBER,
  ask_volume_5           NUMBER,
  average_price          NUMBER,
  action_day             VARCHAR2(9)
)
tablespace marketdatatemp storage (initial 1M next 64M minextents 1 maxextents unlimited) nologging;
commit;
